title: SwiftDotNet
description: Sample full application (client and back-end in separate projects) that demonstrates using Swift for iOS with ASP.NET 4.6.x Web API and MVC on Azure with DocumentDB and Azure Search.
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
